#' infer_metric_for_thr
#'
#' For performance estimation, this function infers whether `mean_log2FoldChange` or `sd_log2FoldChange` should be used for any FDR thresholding.
#'
#' @param data A data frame generated by `delboy::make_delboy_crispr_hit_comparison_table`.
#' 
#' @return A list containing the following components:
#' * `summ_stats`: A data frame summarising median values of `mean_log2FoldChange` and `sd_log2FoldChange` for TPs and FPs.
#' * `metric`: A character string, either: `mean_log2FoldChange`, `sd_log2FoldChange`, or `NA` (no metric to be used for FDR thresholding).
#' @md
#' @export
#' @importFrom dplyr %>% select
#' @importFrom rlang sym !!
infer_metric_for_thr <- function(data){
  tryCatch({
    summ <- data %>%
      dplyr::summarise(mdn.mlfc_tp = median(mean_log2FoldChange[hit_type=="True_Positive"], na.rm=T),
                       mdn.mlfc_fp = median(mean_log2FoldChange[hit_type=="False_Positive"], na.rm=T),
                       mdn.slfc_tp = median(sd_log2FoldChange[hit_type=="True_Positive"], na.rm=T),
                       mdn.slfc_fp = median(sd_log2FoldChange[hit_type=="False_Positive"], na.rm=T))
    if(summ$mdn.mlfc_fp < summ$mdn.mlfc_tp && summ$mdn.slfc_fp < summ$mdn.slfc_tp){
      # FP mean_logFC and sd_logFC both lower than TP.
      metric <- "mean_log2FoldChange"
    }else if(summ$mdn.mlfc_fp > summ$mdn.mlfc_tp && summ$mdn.slfc_fp > summ$mdn.slfc_tp){
      # FP mean_logFC and sd_logFC both greater than TP.
      metric <- "sd_log2FoldChange"
    }else{
      metric <- NA
    }
  },
  error = function(e) stop(paste("unable to infer metric for FDR thresholding:",e))
  )
  return(list(summ_stats = summ,
              metric = metric))
}
