#' make_delboy_crispr_hit_comparison_table
#'
#' Make a TP, FN, FP data frame to aid analysis of `delboy` validation hits produced by `delboy::evaluate_performance_crispr_calls`.
#'
#' @param comb_pvals A data frame generated by `delboy::combine_harmonic_mean_pvals`.
#' @param lfc_samp A named vector of logFC values where the names are gene names. These are the true positives with their associated logFC values. All other genes are true negatives.
#'
#' @return A data frame.
#' @export
#' @importFrom dplyr filter %>% mutate case_when
make_delboy_crispr_hit_comparison_table <- function(comb_pvals, lfc_samp){
  tryCatch({
    if(!"gene" %in% colnames(comb_pvals)) stop("unable to find 'gene' column in 'comb_pvals'")
    hits <- comb_pvals$gene[comb_pvals$significant_hit]
    all_hits <- unique(c(names(lfc_samp), hits))
    TP <- names(lfc_samp)[names(lfc_samp) %in% hits]
    FN <- names(lfc_samp)[!names(lfc_samp) %in% hits]
    FP <- hits[!hits %in% names(lfc_samp)]
    ret <- comb_pvals %>%
      dplyr::filter(gene %in% all_hits) %>%
      dplyr::mutate(log10_baseExpr = log10(mean_baseMean),
                    abs_log2FoldChange = abs(mean_log2FoldChange),
                    hit_type = dplyr::case_when(gene %in% TP ~ "True_Positive",
                                                gene %in% FN ~ "False_Negative",
                                                gene %in% FP ~ "False_Positive"),
                    hit_type = factor(hit_type,levels=c("True_Positive","False_Negative",
                                                        "False_Positive")),
                    lfc_true_mean = lfc_samp[match(gene, names(lfc_samp))])
  },
  error = function(e) stop(paste("unable to build delboy-DESeq2 crispr comparison data frame:",e))
  )
  return(ret)
}
